### ISSUE TITLE
Scriptfehler

### ISSUE THREAD

**Issue by threadstone83** [www-ShapeLabs-de/Judo-i-soft-save-plus-to-mqtt-bridge#23] opened 2024-09-16 20:08 UTC
Since today I get the following script errors and find no solution how to solve that.

2024-09-16 22:03:36.690828 INFO AppDaemon: Calling initialize() for main_app
Lade gespeicherte Variablen
----------------------
Letzte Fehler-ID: 581270
Wasserverbrauch gestern: 416
Offset für heutigen Wasserverbrauch: 31867
Letzte Ausführung des Scripts: 16
da: 0x1
dt: 0x33
serial: 002187732972
token: xxxxxxxxxx
avergage regeneration interval: 52h
counter for avg-calc: 93
last regenerations count: 93
timestamp of last regeneration: 1726383644s
Softwater prop. since Regeneration: 21.814L
Hardwater prop. since Regeneration: 9.81L
Initialisierung erfolgreich!
2024-09-16 22:03:36.850168 INFO AppDaemon: Calling initialize() for hello_world
Verbunden mit MQTT Broker...
Topics wurden abonniert...
Autoconfigs wurden gesendet...
2024-09-16 22:03:37.187090 INFO hello_world: Hello from AppDaemon
2024-09-16 22:03:37.190760 INFO hello_world: You are now ready to run Apps!
2024-09-16 22:03:37.194165 INFO AppDaemon: App initialization complete
['Scriptfehler - Fehler beim Holen und Auswerten der Gerätedaten in Zeile: 402', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Auswerten des Fehlerspeichers in Zeile: 523', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Holen und Auswerten der Gerätedaten in Zeile: 402', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Auswerten des Fehlerspeichers in Zeile: 523', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Holen und Auswerten der Gerätedaten in Zeile: 402', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Auswerten des Fehlerspeichers in Zeile: 523', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Holen und Auswerten der Gerätedaten in Zeile: 402', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Auswerten des Fehlerspeichers in Zeile: 523', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Holen und Auswerten der Gerätedaten in Zeile: 402', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
['Scriptfehler - Fehler beim Auswerten des Fehlerspeichers in Zeile: 523', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
...

Does anyone have the same problem?
Can anyone help? @www-ShapeLabs-de @danielegger1 eventually you?

**Comment by threadstone83** [comment] 2024-09-16 20:56
I played a little bit. Now I get the following error:

['Scriptfehler - Judo-login fehlgeschlagen in Zeile: 293', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]

I tried to access https://www.myjudo.eu/interface/?group=register&command=login&name=login&user={username}&password={pwmd5}&nohash=Service&role=customer but I also get the error, that the login is not possible. At the homepage I can login without any problems but the link looks completely different after login. 

Eventually Judo have changed their login?!

**Comment by threadstone83** [comment] 2024-09-16 21:04
Yes, it looks like Judo have changed something. Also at the iobroker integration they have problems:
https://github.com/arteck/ioBroker.judoisoft/issues/40
https://forum.iobroker.net/topic/40337/test-wasserenth%C3%A4rtung-judo-i-soft-plus-adapter/174

**Comment by hankipanky** [comment] 2024-09-16 21:07
Looks like their API endpoint blocks HTTP requests from scripts, based on the `user-agent` header 🤦 

This works:
```
curl 'https://www.myjudo.eu/interface/?token={token}&group=register&command=get%20device%20data' -H 'User-Agent: Mozilla'
```

Without the user-agent header, or with the default `python-urllib/3`, the response body is empty.

**Comment by threadstone83** [comment] 2024-09-16 21:09
Any idea how to modify the code in getjudo.py (line 292 round about)?

```
def judo_login(username, password):
    pwmd5 = hashlib.md5(password.encode("utf-8")).hexdigest()
    try:
        login_response = http.request('GET', f"https://www.myjudo.eu/interface/?group=register&command=login&name=login&user={username}&password={pwmd5}&nohash=Service&role=customer")
        login_response_json = json.loads(login_response.data)
        if "token" in login_response_json:
            print(messages_getjudo.debug[22].format(login_response_json['token']))
            return login_response_json['token']
        else:
            notify.publish(messages_getjudo.debug[21], 2)
            sys.exit()
    except Exception as e:
        notify.publish([messages_getjudo.debug[28].format(sys.exc_info()[-1].tb_lineno),e], 3)
        sys.exit()
```

**Comment by hankipanky** [comment] 2024-09-16 21:39
The `urllib3.PoolManager` can be instructed to use default headers for all requests:

```python
user_agent = {'user-agent':'Mozilla'}
http = urllib3.PoolManager(10, headers=user_agent)
```

I'll create a PR tomorrow.

**Comment by gmbh07** [comment] 2024-09-17 05:49
i always get this errors but i have no idea what to do, can you help me pls?

['Scriptfehler - Fehler beim Auswerten des Fehlerspeichers in Zeile: 396', "Expecting value: line 1 column 1 (char 0) - b''"]
['Scriptfehler - Fehler beim Auswerten des Fehlerspeichers in Zeile: 500', "Expecting value: line 1 column 1 (char 0) - b''"]

**Comment by hankipanky** [comment] 2024-09-17 06:59
> i always get this errors but i have no idea what to do, can you help me pls?

I've filed a PR (see #24 ). Either you can wait for it to be merged, or you can make the simple change yourself.

**Comment by deluxestyle** [comment] 2024-09-17 07:34
> The `urllib3.PoolManager` can be instructed to use default headers for all requests:
> 
> ```python
> user_agent = {'user-agent':'Mozilla'}
> http = urllib3.PoolManager(10, headers=user_agent)
> ```
> 
> I'll create a PR tomorrow.

seems to work. Thank you

**Comment by gohakn** [comment] 2024-09-17 10:31
For me it also works fine. Thank you

**Comment by udoersam** [comment] 2024-09-17 10:53
I can confirm that the workaround / fix works as aprected. Thanks

**Comment by threadstone83** [comment] 2024-09-17 15:01
I an also confirm. With the code / the workaround all works again. Thank you very much!!

Is it possible to add the the missed consumption values ​​in HA? I think I know how to do it in the energy dashboard, but in the entities?

**Comment by aLimp86** [comment] 2024-09-18 06:25
Can someone describe where to find the "urllib3.PoolManager"? Or how to patch it in detail?

**Comment by Towerlein** [comment] 2024-09-20 04:43
Mein Home Assistant zeigt den gleichen Fehler an. könnt ihr mir bitte erklären, in welcher Datei ihr was verändert habt?
Herzlichen Dank

**Comment by Towerlein** [comment] 2024-09-20 05:14
Ah, if you look you will find. "Deluxstyle".  you are great. How do you come up with a solution like that?
Thank you, for this...
https://github.com/www-ShapeLabs-de/Judo-i-soft-save-plus-to-mqtt-bridge/pull/24/commits/1fb0e0399f62ad99104eb48f84d2c8f2de45b873

**Comment by deluxestyle** [comment] 2024-09-20 05:46
> Ah, if you look you will find. "Deluxstyle". you are great. How do you come up with a solution like that? Thank you, for this... [1fb0e03](https://github.com/www-ShapeLabs-de/Judo-i-soft-save-plus-to-mqtt-bridge/commit/1fb0e0399f62ad99104eb48f84d2c8f2de45b873)

Was not me. It was @hankipanky

**Comment by Towerlein** [comment] 2024-09-20 06:07
oh, sorry that's right, thank you @hankipanky :-)

**Comment by threadstone83** [comment] 2024-09-23 16:30
Since today I have the same error.
@hankipanky do you have a solution again?

EDIT: I had this happen also a few days ago. A reboot fixed it. It seems like I get logged out every 2 days at night.
Anyone have any ideas?

EDIT 2: I don't know what that was, but after I had to restart AppDeamon twice (after it was no longer able to retrieve data), everything has been running as it should for a few days now. So my question is no longer relevant.

**Comment by mike4001** [comment] 2024-10-16 05:57
Since this morning it is not working for me.

Logs say

['Scriptfehler - Fehler beim Holen und Auswerten der Gerätedaten in Zeile: 409', KeyError('7')]

**Comment by gmbh07** [comment] 2024-10-16 06:00
me too, same error

**Comment by mike4001** [comment] 2024-10-16 06:29
OK, it the Integration just correctly updated again.

Probably was just a server-side issue on Judo´s part.

Hope this is it ....

**Comment by deluxestyle** [comment] 2024-10-16 07:16
Mine is working. But it seems there have been no values over night

**Comment by OverDodo** [comment] 2024-12-21 15:45
Anyone else not getting data since some time around yesterday? I tried some API calls via postman and always got a 200 OK but empty response body.. Even for requesting a new token, doesnt even care if its wrong credentials

**Comment by threadstone83** [comment] 2024-12-21 19:36
There is no problem here. Works as it should.

**Closed as completed** 2024-12-21 19:36 UTC
